[package]
name = "event-creator"
version = "0.1.1"
edition = "2024"


[dependencies]
google-cloud-pubsub = "0.30.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
rand = "0.8"